name: dagger
on:
  push:
    branches: [main]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        uses: dagger/dagger-for-github@v6
        with:
            verb: call
            module: github.com/shykes/daggerverse/hello
            args: hello --greeting Hola --name Jeremy
            cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}  

      - name: Build
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
        #   args: build-and-push --registry=$DOCKER_REGISTRY --image-name=$DOCKER_IMAGE_NAME --username=$DOCKER_USERNAME --password=env:DOCKER_PASSWORD --build-context=github.com/daggerverse/dagger-ghcr-demo
          args: --ref ${{ github.ref }} build
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_IMAGE_NAME: ${{ github.repository }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Publish
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
          args: --ref ${{ github.ref }} publish
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_IMAGE_NAME: ${{ github.repository }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}    